# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{simplejob}
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Ken Pratt}]
  s.date = %q{2011-09-07}
  s.description = %q{A simple AMQP-backed job queuing system.}
  s.email = %q{ken@kenpratt.net}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "examples/basic/README.md",
    "examples/basic/consumer.rb",
    "examples/basic/producer.rb",
    "examples/chained_jobs/README.md",
    "examples/chained_jobs/consumer.rb",
    "examples/chained_jobs/producer.rb",
    "examples/multiple_jobs/README.md",
    "examples/multiple_jobs/drink_consumer.rb",
    "examples/multiple_jobs/food_consumer.rb",
    "examples/multiple_jobs/producer.rb",
    "examples/wildcard_handlers/README.md",
    "examples/wildcard_handlers/consumer.rb",
    "examples/wildcard_handlers/producer.rb",
    "examples/wildcard_handlers/wiretap.rb",
    "lib/simplejob.rb",
    "lib/simplejob/client.rb",
    "lib/simplejob/hash_extensions.rb",
    "lib/simplejob/worker.rb",
    "simplejob.gemspec",
    "test/helper.rb",
    "test/test_simplejob.rb"
  ]
  s.homepage = %q{http://github.com/kenpratt/simplejob}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{Painless job queueing.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0.1"])
      s.add_runtime_dependency(%q<json>, [">= 1.5.1"])
      s.add_runtime_dependency(%q<amqp>, ["= 0.7.1"])
    else
      s.add_dependency(%q<activesupport>, [">= 3.0.1"])
      s.add_dependency(%q<json>, [">= 1.5.1"])
      s.add_dependency(%q<amqp>, ["= 0.7.1"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 3.0.1"])
    s.add_dependency(%q<json>, [">= 1.5.1"])
    s.add_dependency(%q<amqp>, ["= 0.7.1"])
  end
end

